ALTER TABLE "User"
ADD COLUMN IF NOT EXISTS "avatarUrl" TEXT;

ALTER TABLE "User"
ADD COLUMN IF NOT EXISTS "provider" TEXT DEFAULT 'local';

ALTER TABLE "User"
ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;